apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama-azure.fullname" . }}
  labels:
    {{- include "ollama-azure.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ollama-azure.selectorLabels" . | nindent 4 }}